import { AIModel, AIMode, PromptTemplate, KnowledgeDoc, UserMemory } from '@/types';

export const AI_MODELS: AIModel[] = [
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    tagline: 'Benchmark leader for coding, nuance, and clean logic',
    badge: 'Flagship',
    contextWindow: '200K tokens',
    speed: '75 t/s',
    reasoningScore: 98,
    codingScore: 99,
    iconName: 'Sparkles',
    accentColor: 'from-amber-500 to-orange-600',
  },
  {
    id: 'deepseek-coder-v2',
    name: 'DeepSeek Coder V2',
    provider: 'DeepSeek',
    tagline: 'Exceptional code generation, debugging, and architecture',
    badge: 'Code Expert',
    contextWindow: '128K tokens',
    speed: '85 t/s',
    reasoningScore: 95,
    codingScore: 98,
    iconName: 'Code',
    accentColor: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'llama-3-70b',
    name: 'Llama 3 70B',
    provider: 'Meta AI',
    tagline: 'Ultra-fast open weights powerhouse for versatile reasoning',
    badge: 'Ultra Fast',
    contextWindow: '128K tokens',
    speed: '110 t/s',
    reasoningScore: 93,
    codingScore: 91,
    iconName: 'Zap',
    accentColor: 'from-purple-500 to-indigo-600',
  },
  {
    id: 'qwen-2-5-72b',
    name: 'Qwen 2.5 72B',
    provider: 'Alibaba Cloud',
    tagline: 'SOTA mathematics, multilingual translation, and reasoning',
    badge: 'Math & Logic',
    contextWindow: '128K tokens',
    speed: '80 t/s',
    reasoningScore: 96,
    codingScore: 94,
    iconName: 'Cpu',
    accentColor: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'mistral-large',
    name: 'Mistral Large 2',
    provider: 'Mistral AI',
    tagline: 'European frontier model with high precision and concise answers',
    badge: 'High Precision',
    contextWindow: '128K tokens',
    speed: '70 t/s',
    reasoningScore: 94,
    codingScore: 92,
    iconName: 'Shield',
    accentColor: 'from-pink-500 to-rose-600',
  },
];

export const AI_MODES: AIMode[] = [
  {
    id: 'balanced',
    name: 'Balanced',
    description: 'Everyday assistance, natural conversations, and balanced insights.',
    iconName: 'Scale',
    badgeColor: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
    temperature: 0.7,
    systemPromptAddon: 'Provide balanced, engaging, and comprehensive answers with clear structure.',
  },
  {
    id: 'coding',
    name: 'Coding',
    description: 'DeepSeek-style programming, clean code, tests, and debugging.',
    iconName: 'Terminal',
    badgeColor: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
    temperature: 0.2,
    systemPromptAddon: 'You are an elite software architect. Output clean, modular, production-ready code with complete type safety, inline documentation, and error handling. Whenever creating a UI or complete widget, produce code formatted in markdown codeblocks so the user can interact with the live Artifact panel.',
  },
  {
    id: 'research',
    name: 'Deep Research',
    description: 'Perplexity-style multi-source analysis with grounded citations.',
    iconName: 'Globe',
    badgeColor: 'bg-purple-500/20 text-purple-400 border-purple-500/30',
    temperature: 0.3,
    systemPromptAddon: 'Synthesize verified information, compare perspectives, and always reference numbered citations [1], [2] to indicate verified sources.',
  },
  {
    id: 'creative',
    name: 'Creative',
    description: 'Vibrant writing, storytelling, marketing copy, and metaphors.',
    iconName: 'Feather',
    badgeColor: 'bg-pink-500/20 text-pink-400 border-pink-500/30',
    temperature: 0.9,
    systemPromptAddon: 'Adopt a compelling, vivid, and highly creative tone with rich analogies and memorable hooks.',
  },
  {
    id: 'precise',
    name: 'Precise',
    description: 'Strictly factual, concise, and mathematically rigorous responses.',
    iconName: 'Target',
    badgeColor: 'bg-cyan-500/20 text-cyan-400 border-cyan-500/30',
    temperature: 0.1,
    systemPromptAddon: 'Be extremely concise, fact-checked, bulleted where appropriate, avoiding fluff or unnecessary pleasantries.',
  },
  {
    id: 'document',
    name: 'Document AI',
    description: 'Deep comprehension of uploaded PDFs, spreadsheets, and specs.',
    iconName: 'FileText',
    badgeColor: 'bg-amber-500/20 text-amber-400 border-amber-500/30',
    temperature: 0.2,
    systemPromptAddon: 'Focus on extracting exact information, tabular data, key metrics, and executive summaries from provided documents.',
  },
];

export const DEFAULT_PROMPT_LIBRARY: PromptTemplate[] = [
  {
    id: 'p-1',
    title: 'Modern React Component with Tailwind',
    category: 'Coding',
    description: 'Generate a production-ready, accessible React component with glassmorphism styles and micro-interactions.',
    prompt: 'Build an interactive, modern React TypeScript component for a sleek dark-mode glassmorphic widget. Include full Tailwind styling, hover animations, accessibility ARIA attributes, and state management.',
    tags: ['React', 'TypeScript', 'Tailwind', 'UI'],
    iconName: 'Layout',
  },
  {
    id: 'p-2',
    title: 'Full-Stack API Design & Schema',
    category: 'Coding',
    description: 'Design a clean REST / GraphQL API schema with PostgreSQL tables and indexing.',
    prompt: 'Design a production-grade database schema in PostgreSQL and corresponding REST API endpoints for a scalable SaaS platform. Include foreign keys, indexes, security checks, and sample TypeScript interfaces.',
    tags: ['Database', 'PostgreSQL', 'API', 'Backend'],
    iconName: 'Database',
  },
  {
    id: 'p-3',
    title: 'Viral Tech LinkedIn Post',
    category: 'Marketing',
    description: 'Write an engaging, high-retention post analyzing latest AI industry breakthroughs.',
    prompt: 'Write a viral, thought-provoking LinkedIn post breaking down the paradigm shift from traditional software to AI agent workflows. Use an irresistible hook, structured bullet insights, concrete metrics, and a discussion-provoking question at the end.',
    tags: ['LinkedIn', 'Copywriting', 'AI', 'Growth'],
    iconName: 'Share2',
  },
  {
    id: 'p-4',
    title: 'Executive Summary & Tech Comparison',
    category: 'Business',
    description: 'Create a structured decision matrix comparing architectural approaches.',
    prompt: 'Prepare an executive-level technology evaluation comparing Vector Databases (Pinecone vs Qdrant vs pgvector) for enterprise RAG workflows. Include latency, cost per 1M vectors, ease of maintenance, and final recommendation for a high-growth startup.',
    tags: ['Strategy', 'Architecture', 'RAG', 'VectorDB'],
    iconName: 'TrendingUp',
  },
  {
    id: 'p-5',
    title: 'High-Converting Cold Email Sequence',
    category: 'Marketing',
    description: '3-stage B2B cold outreach email sequence targeting VP of Engineering.',
    prompt: 'Write a 3-part B2B cold email sequence for an AI engineering tool targeting VPs of Engineering. Keep each email under 120 words, hyper-personalized, focused on reducing cloud bill by 40%, with zero pushy fluff.',
    tags: ['Sales', 'Email', 'B2B', 'Copywriting'],
    iconName: 'Mail',
  },
  {
    id: 'p-6',
    title: 'Complex Algorithm & Complexity Breakdown',
    category: 'Education',
    description: 'Explain distributed consensus algorithms like Raft / Paxos with diagrams and code.',
    prompt: 'Explain the Raft Consensus Algorithm in intuitive steps. Break down Leader Election, Log Replication, and Safety guarantees. Include pseudocode and ASCII diagrams to illustrate node state transitions.',
    tags: ['Algorithms', 'Distributed Systems', 'Computer Science'],
    iconName: 'BookOpen',
  },
  {
    id: 'p-7',
    title: 'Daily High-Leverage Planner',
    category: 'Productivity',
    description: 'Time-block your day using the Eisenhower Matrix and deep work principles.',
    prompt: 'Help me organize my work day for maximum leverage. Ask me for my top 5 tasks, then categorize them into Urgent/Important, schedule 90-minute Deep Work blocks, and output a structured timeline.',
    tags: ['Productivity', 'Time Management', 'Deep Work'],
    iconName: 'CheckCircle',
  },
  {
    id: 'p-8',
    title: 'Academic Paper Deep Summarizer',
    category: 'Writing',
    description: 'Distill 30-page research papers into methodology, contributions, and caveats.',
    prompt: 'Summarize the core breakthrough of the provided research paper. Structure the breakdown into: 1. Core Problem, 2. Novel Architecture/Method, 3. Empirical Results & Baselines, 4. Critical Limitations, 5. Practical Engineering Takeaways.',
    tags: ['Research', 'Summarizer', 'Papers', 'Science'],
    iconName: 'FileText',
  },
  {
    id: 'p-9',
    title: 'Friendly Tanglish Coding Mentor (தமிழ் & English)',
    category: 'Coding',
    description: 'Explain coding concepts, debug errors, and write full code in friendly, natural Tanglish.',
    prompt: 'Enakku indha coding topic pathi super simple-aa, real-life examples vachu Tanglish-la explain pannu bro. Step-by-step code and clear tips thanga!',
    tags: ['Tanglish', 'Tamil', 'Coding', 'Mentor'],
    iconName: 'Terminal',
  },
  {
    id: 'p-10',
    title: 'Friendly Tech Peer Chat (Tanglish Buddy)',
    category: 'Education',
    description: 'Chat naturally like human friends about tech, careers, project ideas, or everyday topics.',
    prompt: 'Hey! Namma jolly-aa friendly-aa chat pannuvom. Enakku pudhu tech ideas & career tips venum. Simple Tanglish-la advice thanga!',
    tags: ['Tanglish', 'Friendly Chat', 'Career', 'Peer'],
    iconName: 'Smile',
  }
];

export const INITIAL_USER_MEMORIES: UserMemory[] = [
  {
    id: 'm-0',
    content: 'Enjoys natural, warm, and friendly conversations in Tanglish and English like chatting with a supportive human friend and tech peer.',
    category: 'personal',
    createdAt: Date.now() - 86400000 * 4,
    isActive: true,
  },
  {
    id: 'm-1',
    content: 'Prefers TypeScript with strict types and modern React functional components with Tailwind CSS.',
    category: 'coding',
    createdAt: Date.now() - 86400000 * 3,
    isActive: true,
  },
  {
    id: 'm-2',
    content: 'Works as an innovative software developer designing modern AI applications and full-stack web platforms.',
    category: 'work',
    createdAt: Date.now() - 86400000 * 2,
    isActive: true,
  },
  {
    id: 'm-3',
    content: 'Prefers dark-mode glassmorphic UI designs with electric blue and purple accents.',
    category: 'preference',
    createdAt: Date.now() - 86400000,
    isActive: true,
  },
];

export const INITIAL_KNOWLEDGE_DOCS: KnowledgeDoc[] = [
  {
    id: 'doc-zenix-architecture',
    title: 'Zenix AI Platform Architecture Whitepaper (v2.4)',
    type: 'PDF',
    size: 2450000,
    uploadedAt: Date.now() - 86400000 * 5,
    chunkCount: 8,
    tags: ['Architecture', 'RAG', 'VectorDB', 'Embeddings'],
    chunks: [
      {
        id: 'chunk-1',
        docId: 'doc-zenix-architecture',
        docTitle: 'Zenix AI Platform Architecture Whitepaper (v2.4)',
        chunkIndex: 0,
        text: 'Zenix AI employs a hybrid dense-sparse vector indexing pipeline utilizing bge-large-en embeddings mapped across a 1024-dimensional semantic space for sub-10ms similarity searches.',
      },
      {
        id: 'chunk-2',
        docId: 'doc-zenix-architecture',
        docTitle: 'Zenix AI Platform Architecture Whitepaper (v2.4)',
        chunkIndex: 1,
        text: 'To minimize hallucinations, all retrieved document chunks are reranked using cross-encoder models before injection into the LLM context window alongside exact page coordinates.',
      },
      {
        id: 'chunk-3',
        docId: 'doc-zenix-architecture',
        docTitle: 'Zenix AI Platform Architecture Whitepaper (v2.4)',
        chunkIndex: 2,
        text: 'Streaming token generation utilizes HTTP/2 Server-Sent Events (SSE) with bidirectional cancel signals, guaranteeing instant response pause upon user interruption.',
      },
      {
        id: 'chunk-4',
        docId: 'doc-zenix-architecture',
        docTitle: 'Zenix AI Platform Architecture Whitepaper (v2.4)',
        chunkIndex: 3,
        text: 'Artifact isolation runs within sandboxed browser iframes using Content Security Policy (CSP) headers, enabling real-time preview of HTML, SVG, and interactive React widgets without XSS vulnerability.',
      }
    ]
  },
  {
    id: 'doc-deepseek-perf',
    title: 'DeepSeek-Coder-V2 Performance & Multi-Language Evaluation',
    type: 'DOCX',
    size: 1820000,
    uploadedAt: Date.now() - 86400000 * 2,
    chunkCount: 5,
    tags: ['DeepSeek', 'Benchmarks', 'Coding', 'Python', 'Rust'],
    chunks: [
      {
        id: 'chunk-ds-1',
        docId: 'doc-deepseek-perf',
        docTitle: 'DeepSeek-Coder-V2 Performance & Multi-Language Evaluation',
        chunkIndex: 0,
        text: 'DeepSeek Coder V2 achieves 90.2% HumanEval pass@1 rate, demonstrating superior syntax parsing across 338 programming languages with specialized Fill-In-the-Middle (FIM) optimization.',
      },
      {
        id: 'chunk-ds-2',
        docId: 'doc-deepseek-perf',
        docTitle: 'DeepSeek-Coder-V2 Performance & Multi-Language Evaluation',
        chunkIndex: 1,
        text: 'The model demonstrates extraordinary proficiency in code refactoring, AST transformations, SQL query optimization, and generating unit test mocks with edge-case coverage.',
      }
    ]
  }
];
