import { ChatSession } from '@/types';

export function exportChatAsMarkdown(session: ChatSession): string {
  let md = `# ${session.title}\n\n`;
  md += `*Generated by Zenix AI on ${new Date(session.createdAt).toLocaleString()}*\n`;
  md += `*Model: ${session.modelId} | Mode: ${session.modeId}*\n\n---\n\n`;

  for (const msg of session.messages) {
    const roleName = msg.role === 'user' ? '👤 **You**' : '✨ **Zenix AI**';
    md += `### ${roleName} (${new Date(msg.timestamp).toLocaleTimeString()})\n\n`;
    md += `${msg.content}\n\n`;

    if (msg.citations && msg.citations.length > 0) {
      md += `**Citations & Sources:**\n`;
      msg.citations.forEach((c, idx) => {
        md += `- [${idx + 1}] [${c.title}](${c.url}) - *${c.domain}*\n`;
      });
      md += `\n`;
    }

    if (msg.artifacts && msg.artifacts.length > 0) {
      for (const art of msg.artifacts) {
        md += `\`\`\`${art.language}\n// Artifact: ${art.title}\n${art.code}\n\`\`\`\n\n`;
      }
    }
    md += `---\n\n`;
  }

  return md;
}

export function exportChatAsPlainText(session: ChatSession): string {
  let txt = `ZENIX AI CONVERSATION EXPORT\n`;
  txt += `Title: ${session.title}\n`;
  txt += `Date: ${new Date(session.createdAt).toLocaleString()}\n`;
  txt += `Model: ${session.modelId}\n`;
  txt += `========================================================\n\n`;

  for (const msg of session.messages) {
    const role = msg.role.toUpperCase();
    txt += `[${role}] - ${new Date(msg.timestamp).toLocaleTimeString()}\n`;
    txt += `${msg.content}\n\n`;
    if (msg.citations && msg.citations.length > 0) {
      txt += `Sources:\n`;
      msg.citations.forEach((c, idx) => {
        txt += `  [${idx + 1}] ${c.title} (${c.url})\n`;
      });
      txt += `\n`;
    }
    txt += `--------------------------------------------------------\n\n`;
  }

  return txt;
}

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function triggerPrintChat() {
  window.print();
}
